remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: ✒️Ian Gigante's CV
description: This page contains the summary of my 10yrs journey as a Quality Assurance Engineer
